version: '3'
services:
  dev:
    build: .
    entrypoint: [sh, -c, wait-for-it -t 100 hive-server:10000 && sleep 1 && exec "$$@", -]
    command: bash
    environment:
      HIVE_DB_HOST: hive-server
      HIVE_DB_PORT: 10000
      HIVE_DB_DATABASE: default
      HIVE_DB_USER: admin
      HIVE_DB_PASSWORD: p#a!s@sw:o&r%^d
    volumes:
      - ./:/code
    links:
      - hive-server

  # LDAP authentication server for Hive (external auth must be provided)
  # Test cmd: docker-compose exec ldap ldapsearch -x -H ldap://localhost -b dc=keboola-test,dc=com -D "cn=admin,dc=keboola-test,dc=com" -w 'p#a!s@sw:o&r%^d'
  ldap:
    image: osixia/openldap:1.3.0-amd64
    command: --copy-service
    environment:
      LDAP_TLS: 'false'
      LDAP_ORGANISATION: Keboola Test
      LDAP_DOMAIN: keboola-test.com
      LDAP_ADMIN_PASSWORD: p#a!s@sw:o&r%^d


  # Hive infrastructure
  # From: https://github.com/big-data-europe/docker-hive/blob/master/docker-compose.yml
  # Test cmd: docker-compose exec hive-server beeline -u jdbc:hive2://localhost:10000 -n admin -p 'p#a!s@sw:o&r%^d' -e "SHOW TABLES;"
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - docker-hive/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
      HIVE_SITE_CONF_hive_server2_use_SSL: 'false'
      HIVE_SITE_CONF_hive_server2_authentication: LDAP
      HIVE_SITE_CONF_hive_server2_authentication_ldap_url: ldap://ldap:389
      HIVE_SITE_CONF_hive_server2_authentication_ldap_baseDN: dc=keboola-test,dc=com
      HIVE_SITE_CONF_hive_server2_authentication_ldap_userDNPattern: cn=%s,dc=keboola-test,dc=com
      HIVE_SITE_CONF_hive_server2_logging_operation_enabled: 'true'
      HIVE_SITE_CONF_hive_server2_logging_operation_level: VERBOSE
    links:
      - ldap
      - namenode
      - datanode
      - presto-coordinator
      - hive-metastore
      - hive-metastore-postgresql
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker-hive/hadoop-hive.env
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - docker-hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - docker-hive/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
  presto-coordinator:
    image: shawnzhu/prestodb:0.181

volumes:
  namenode:
  datanode:
